# Generated by Django 4.1.7 on 2023-03-25 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cipherGame', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scoremodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='cipherGame.userdatamodel'),
        ),
    ]
