# Generated by Django 4.1.7 on 2023-04-29 16:02

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cipherGame', '0003_gamemode_scoremodel_game_mode'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameIDModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_id', models.UUIDField(default=uuid.uuid4, editable=False)),
            ],
        ),
        migrations.AddField(
            model_name='scoremodel',
            name='game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='cipherGame.gameidmodel'),
        ),
    ]
