# Generated by Django 4.1.7 on 2023-06-05 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cipherGame', '0006_alter_scoremodel_game_mode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scoremodel',
            name='game_mode',
        ),
        migrations.DeleteModel(
            name='GameMode',
        ),
    ]
