# Generated by Django 4.1.7 on 2023-06-05 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cipherGame', '0008_gamemode_scoremodel_game_mode'),
    ]

    operations = [
        migrations.CreateModel(
            name='MachineGameDataModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=30)),
                ('score', models.IntegerField(blank=True)),
                ('time', models.IntegerField(blank=True)),
                ('date', models.DateField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='MultiplayerGameDataModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=30)),
                ('score', models.IntegerField(blank=True)),
                ('time', models.IntegerField(blank=True)),
                ('date', models.DateField(blank=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='scoremodel',
            name='game',
        ),
        migrations.RemoveField(
            model_name='scoremodel',
            name='game_mode',
        ),
        migrations.DeleteModel(
            name='GameIDModel',
        ),
        migrations.DeleteModel(
            name='GameMode',
        ),
    ]
